Overwatch Maker/Controllers/AbilitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Overwatch_Maker.Models;

namespace Overwatch_Maker.Controllers
{
    public class AbilitiesController : Controller
    {
        private OverwatchDBEntities db = new OverwatchDBEntities();

        // GET: Abilities
        public async Task<ActionResult> Index()
        {
            return View(await db.Abilities.ToListAsync());
        }

        // GET: Abilities/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ability ability = await db.Abilities.FindAsync(id);
            if (ability == null)
            {
                return HttpNotFound();
            }
            return View(ability);
        }

        // GET: Abilities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Abilities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "AbilityID,Type,Name,Description,Duration,Strenght")] Ability ability)
        {
            if (ModelState.IsValid)
            {
                db.Abilities.Add(ability);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(ability);
        }

        // GET: Abilities/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ability ability = await db.Abilities.FindAsync(id);
            if (ability == null)
            {
                return HttpNotFound();
            }
            return View(ability);
        }

        // POST: Abilities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "AbilityID,Type,Name,Description,Duration,Strenght")] Ability ability)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ability).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(ability);
        }

        // GET: Abilities/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ability ability = await db.Abilities.FindAsync(id);
            if (ability == null)
            {
                return HttpNotFound();
            }
            return View(ability);
        }

        // POST: Abilities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Ability ability = await db.Abilities.FindAsync(id);
            db.Abilities.Remove(ability);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Overwatch Maker/Controllers/HeroesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Overwatch_Maker.Models;

namespace Overwatch_Maker.Controllers
{
    public class HeroesController : Controller
    {
        private OverwatchDBEntities db = new OverwatchDBEntities();

        // GET: Heroes
        public async Task<ActionResult> Index()
        {
            var heroes = db.Heroes.Include(h => h.Ability).Include(h => h.Weapon);
            return View(await heroes.ToListAsync());
        }

        // GET: Heroes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hero hero = await db.Heroes.FindAsync(id);
            if (hero == null)
            {
                return HttpNotFound();
            }
            return View(hero);
        }

        // GET: Heroes/Create
        public ActionResult Create()
        {
            ViewBag.AbilityID = new SelectList(db.Abilities, "AbilityID", "Type");
            ViewBag.WeaponID = new SelectList(db.Weapons, "WeaponID", "Name");
            return View();
        }

        // POST: Heroes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "HeroID,Name,Role,WeaponID,AbilityID,Health,Image")] Hero hero)
        {
            if (ModelState.IsValid)
            {
                db.Heroes.Add(hero);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.AbilityID = new SelectList(db.Abilities, "AbilityID", "Type", hero.AbilityID);
            ViewBag.WeaponID = new SelectList(db.Weapons, "WeaponID", "Name", hero.WeaponID);
            return View(hero);
        }

        // GET: Heroes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hero hero = await db.Heroes.FindAsync(id);
            if (hero == null)
            {
                return HttpNotFound();
            }
            ViewBag.AbilityID = new SelectList(db.Abilities, "AbilityID", "Type", hero.AbilityID);
            ViewBag.WeaponID = new SelectList(db.Weapons, "WeaponID", "Name", hero.WeaponID);
            return View(hero);
        }

        // POST: Heroes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "HeroID,Name,Role,WeaponID,AbilityID,Health,Image")] Hero hero)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hero).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AbilityID = new SelectList(db.Abilities, "AbilityID", "Type", hero.AbilityID);
            ViewBag.WeaponID = new SelectList(db.Weapons, "WeaponID", "Name", hero.WeaponID);
            return View(hero);
        }

        // GET: Heroes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hero hero = await db.Heroes.FindAsync(id);
            if (hero == null)
            {
                return HttpNotFound();
            }
            return View(hero);
        }

        // POST: Heroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Hero hero = await db.Heroes.FindAsync(id);
            db.Heroes.Remove(hero);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Overwatch Maker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Overwatch_Maker.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Overwatch Maker/Controllers/WeaponsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Overwatch_Maker.Models;

namespace Overwatch_Maker.Controllers
{
    public class WeaponsController : Controller
    {
        private OverwatchDBEntities db = new OverwatchDBEntities();

        // GET: Weapons
        public async Task<ActionResult> Index()
        {
            return View(await db.Weapons.ToListAsync());
        }

        // GET: Weapons/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Weapon weapon = await db.Weapons.FindAsync(id);
            if (weapon == null)
            {
                return HttpNotFound();
            }
            return View(weapon);
        }

        // GET: Weapons/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Weapons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "WeaponID,Name,Type,Ammo,ReloadTime,Damage_Heal,Image")] Weapon weapon)
        {
            if (ModelState.IsValid)
            {
                db.Weapons.Add(weapon);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(weapon);
        }

        // GET: Weapons/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Weapon weapon = await db.Weapons.FindAsync(id);
            if (weapon == null)
            {
                return HttpNotFound();
            }
            return View(weapon);
        }

        // POST: Weapons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "WeaponID,Name,Type,Ammo,ReloadTime,Damage_Heal,Image")] Weapon weapon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(weapon).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(weapon);
        }

        // GET: Weapons/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Weapon weapon = await db.Weapons.FindAsync(id);
            if (weapon == null)
            {
                return HttpNotFound();
            }
            return View(weapon);
        }

        // POST: Weapons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Weapon weapon = await db.Weapons.FindAsync(id);
            db.Weapons.Remove(weapon);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Overwatch Maker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<br />
<h2>Overwatch Maker</h2>
<h3>Where imagination is your only limit</h3>

<p>Simply create new weapons, abilities and heros, as well as edit and delete them.</p>

Overwatch Maker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Overwatch Maker/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="margin-top: 13px;">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            <li data-target="#carousel-example-generic" data-slide-to="5"></li>
            <li data-target="#carousel-example-generic" data-slide-to="6"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox" >
            <div class="item active">
                <img src="~/Content/SlideShowImages/ow1.jpg">
                <div class="carousel-caption">
                    Reaper | DPS | Damage
                </div>
            </div>
            <div class="item">
                <img src="~/Content/SlideShowImages/ow2.jpg">
                <div class="carousel-caption">
                    Ana | Support | Heal
                </div>
            </div>
            <div class="item">
                <img src="~/Content/SlideShowImages/ow3.jpg">
                <div class="carousel-caption">
                    Hammond | Tank | Wrecking Ball
                </div>
            </div>
            <div class="item">
                <img src="~/Content/SlideShowImages/ow4.jpg">
                <div class="carousel-caption">
                    Sombra | DPS | Hack
                </div>
            </div>
            <div class="item">
                <img src="~/Content/SlideShowImages/ow5.jpg">
                <div class="carousel-caption">
                    Ana | Support | Heal
                </div>
            </div>
            <div class="item">
                <img src="~/Content/SlideShowImages/ow6.jpg">
                <div class="carousel-caption">
                    Hammond | Tank | Wrecking Ball
                </div>
            </div>
            <div class="item">
                <img src="~/Content/SlideShowImages/ow7.jpg">
                <div class="carousel-caption">
                    Sombra | DPS | Hack
                </div>
            </div>


        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Weapons</h2>
            <p>
                Explore, Create or Delete Weapons for Heroes.
            </p>
            <p>@Html.ActionLink("Learn More", "Index", "Weapons", new { @class = "btn btn-default" })</p>
        </div>
        <div class="col-md-4">
            <h2>Heroes</h2>
            <p>
                Explore, Create or Delete Heroes.
            </p>
            <p>@Html.ActionLink("Learn More", "Index", "Heroes", new { @class = "btn btn-default" })</p>
        </div>
        <div class="col-md-4">
            <h2>Abilities</h2>
            <p>
                Explore, Create or Delete Abilities for Heroes.
            </p>
            <p>@Html.ActionLink("Learn More", "Index", "Abilities", new { @class = "btn btn-default" })</p>
        </div>
    </div>